strictness: veryhigh
doc-warnings: no
test-warnings: no

python-targets:
  - 3

ignore-patterns:
  - (^|/)docs(/|$)

requirements:
  - requirements/base.txt
  - requirements/local.txt
  - requirements/production.txt
  - requirements/test.txt

pep8:
  full: true

uses:
  - django

pylint:
  disable-msg:
    - too-many-ancestors
