sudo: true

language: python
python:
  - "3.5"
addons:
  postgresql: "9.4"

env:
  - DJANGO_SETTINGS_MODULE="config.settings.test"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential gettext python-dev zlib1g-dev libpq-dev xvfb
  - sudo apt-get install -qq libtiff4-dev libjpeg8-dev libfreetype6-dev liblcms1-dev libwebp-dev
  - sudo apt-get install -qq graphviz-dev python-setuptools python3-dev python-virtualenv python-pip
  - sudo apt-get install -qq firefox automake libtool libreadline6 libreadline6-dev libreadline-dev
  - sudo apt-get install -qq libsqlite3-dev libxml2 libxml2-dev libssl-dev libbz2-dev wget curl llvm

install:
  - pip install -r requirements_test.txt

script:
  - flake8 .
  - coverage run manage.py test
  - coverage xml
  - python-codacy-coverage -r coverage.xml
