# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0002_initial_barcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the flow cell <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.', null=True),
        ),
    ]
