# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0002_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowcell',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
