# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0003_flowcell_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodeset',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the barcode set. <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.', null=True),
        ),
        migrations.AlterField(
            model_name='barcodesetentry',
            name='barcode_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='flowcells.BarcodeSet'),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='sequencing_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowcells.SequencingMachine'),
        ),
        migrations.AlterField(
            model_name='library',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowcells.BarcodeSetEntry'),
        ),
        migrations.AlterField(
            model_name='library',
            name='barcode2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcodes2', to='flowcells.BarcodeSetEntry'),
        ),
        migrations.AlterField(
            model_name='library',
            name='barcode_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flowcells.BarcodeSet'),
        ),
        migrations.AlterField(
            model_name='library',
            name='barcode_set2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barcode_sets2', to='flowcells.BarcodeSet'),
        ),
        migrations.AlterField(
            model_name='sequencingmachine',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of the machine. <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.', null=True),
        ),
        migrations.AlterField(
            model_name='sequencingmachine',
            name='machine_model',
            field=models.CharField(choices=[('MiSeq', 'MiSeq'), ('MiniSeq', 'MiniSeq'), ('NextSeq500', 'NextSeq 500'), ('HiSeq1000', 'HiSeq 1000'), ('HiSeq1500', 'HiSeq 1500'), ('HiSeq3000', 'HiSeq 3000'), ('HiSeq4000', 'HiSeq 4000'), ('other', 'Other')], help_text='The model of the machine', max_length=100),
        ),
    ]
