# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-19 09:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0004_auto_20161221_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='info_adapters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowcell',
            name='info_quality_scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
