# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-20 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def create_uuid(app_name, klass_name):
    def fun(apps, schema_editor):
        klass = apps.get_model(app_name, klass_name)
        for obj in klass.objects.all():
            obj.uuid = uuid.uuid4()
            obj.save()
    return fun


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0006_auto_20180320_0622'),
    ]

    operations = [
        migrations.RunPython(create_uuid('flowcells', 'BarcodeSet')),
        migrations.RunPython(create_uuid('flowcells', 'BarcodeSetEntry')),
        migrations.RunPython(create_uuid('flowcells', 'FlowCell')),
        migrations.RunPython(create_uuid('flowcells', 'Library')),
        migrations.RunPython(create_uuid('flowcells', 'SequencingMachine')),
    ]
