# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 16:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0008_auto_20180320_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcodeset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='barcodesetentry',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='index_read_count',
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='is_paired',
        ),
        migrations.RemoveField(
            model_name='flowcell',
            name='read_length',
        ),
        migrations.AddField(
            model_name='flowcell',
            name='info_final_reads',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowcell',
            name='info_planned_reads',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barcodeset',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='barcodesetentry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='status',
            field=models.CharField(choices=[('initial', 'initial'), ('seq_complete', 'sequecing complete'), ('seq_released', 'sequecing released'), ('seq_failed', 'sequencing failed'), ('demux_complete', 'demultiplexing complete'), ('demux_failed', 'demultiplexing failed'), ('demux_started', 'demultiplexing started'), ('demux_delivered', 'demultiplexing results delivered'), ('bcl_delivered', 'base calls delivered')], default='initial', help_text='Processing status of flow cell', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sequencingmachine',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='status',
            field=models.CharField(choices=[('initial', 'initial'), ('seq_running', 'sequencing running'), ('seq_complete', 'sequecing complete'), ('seq_released', 'sequecing released'), ('seq_failed', 'sequencing failed'), ('demux_complete', 'demultiplexing complete'), ('demux_failed', 'demultiplexing failed'), ('demux_started', 'demultiplexing started'), ('demux_delivered', 'demultiplexing results delivered'), ('bcl_delivered', 'base calls delivered')], default='initial', help_text='Processing status of flow cell', max_length=50),
        ),
    ]
