# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models


FLOWCELL_STATUS_INITIAL = 'initial'
FLOWCELL_STATUS_SEQ_RUNNING = 'seq_running'
FLOWCELL_STATUS_SEQ_COMPLETE = 'seq_complete'
FLOWCELL_STATUS_SEQ_RELEASED = 'seq_released'
FLOWCELL_STATUS_SEQ_FAILED = 'seq_failed'
FLOWCELL_STATUS_DEMUX_STARTED = 'demux_started'
FLOWCELL_STATUS_DEMUX_FAILED = 'demux_failed'
FLOWCELL_STATUS_DEMUX_COMPLETE = 'demux_complete'
FLOWCELL_STATUS_DEMUX_DELIVERED = 'demux_delivered'
FLOWCELL_STATUS_BCL_DELIVERED = 'bcl_delivered'


def fill_statuses(apps, schema_editor):
    """Fill the ``status_*`` fields."""
    FlowCell = apps.get_model('flowcells', 'FlowCell')
    for flowcell in FlowCell.objects.all():
        if flowcell.status == 'seq_running':
            flowcell.status_sequencing = 'in_progress'
        elif flowcell.status in ('seq_complete', 'seq_released'):
            flowcell.status_sequencing = 'closed'
        elif flowcell.status == 'seq_failed':
            flowcell.status_sequencing = 'canceled'
        elif flowcell.status == 'demux_started':
            flowcell.status_sequencing = 'closed'
            flowcell.status_conversion = 'in_progress'
        elif flowcell.status == 'demux_failed':
            flowcell.status_sequencing = 'closed'
            flowcell.status_conversion = 'canceled'
        elif flowcell.status == 'demux_delivered':
            flowcell.status_sequencing = 'closed'
            flowcell.status_conversion = 'closed'
            flowcell.status_delivery = 'closed'
        elif flowcell.status == 'bcl_delivered':
            flowcell.status_sequencing = 'closed'
            flowcell.status_conversion = 'closed'
            flowcell.status_delivery = 'closed'
            flowcell.delivery_type = 'bcl'
        flowcell.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0009_auto_20180321_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='delivery_type',
            field=models.CharField(choices=[('seq', 'sequences'), ('bcl', 'base calls'), ('seq_bcl', 'sequences + base calls')], default='seq', help_text='Choices for data delivery type', max_length=50),
        ),
        migrations.AddField(
            model_name='flowcell',
            name='status_conversion',
            field=models.CharField(choices=[('initial', 'not started'), ('in_progress', 'in progress'), ('complete', 'complete'), ('failed', 'failed'), ('closed', 'released'), ('canceled', 'failured confirmed')], default='initial', help_text='Choices for sequencing', max_length=50),
        ),
        migrations.AddField(
            model_name='flowcell',
            name='status_delivery',
            field=models.CharField(choices=[('initial', 'not started'), ('in_progress', 'in progress'), ('complete', 'complete'), ('closed', 'received'), ('failed', 'canceled'), ('canceled', 'canceled confirmed')], default='initial', help_text='Choices for sequencing', max_length=50),
        ),
        migrations.AddField(
            model_name='flowcell',
            name='status_sequencing',
            field=models.CharField(choices=[('initial', 'not started'), ('in_progress', 'in progress'), ('complete', 'complete'), ('closed', 'released'), ('failed', 'failed'), ('canceled', 'failured confirmed')], default='initial', help_text='Choices for sequencing', max_length=50),
        ),
        migrations.RunPython(fill_statuses),
    ]
