# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0011_remove_flowcell_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='manual_label',
            field=models.CharField(blank=True, help_text='Manual label for overriding the one from the folder name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='status_conversion',
            field=models.CharField(choices=[('initial', 'not started'), ('in_progress', 'in progress'), ('complete', 'complete'), ('failed', 'failed'), ('closed', 'released'), ('canceled', 'failured confirmed'), ('skipped', 'skipped')], default='initial', help_text='Choices for sequencing', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='status_delivery',
            field=models.CharField(choices=[('initial', 'not started'), ('in_progress', 'in progress'), ('complete', 'complete'), ('closed', 'received'), ('failed', 'canceled'), ('canceled', 'canceled confirmed'), ('skipped', 'skipped')], default='initial', help_text='Choices for sequencing', max_length=50),
        ),
    ]
