# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0012_auto_20180621_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowcell',
            name='status_conversion',
            field=models.CharField(choices=[('initial', 'keep unstarted'), ('ready', 'ready to start'), ('in_progress', 'in progress'), ('complete', 'complete'), ('complete_warnings', 'complete with warnings'), ('failed', 'failed'), ('closed', 'released'), ('canceled', 'failured confirmed'), ('skipped', 'skipped')], default='initial', help_text='Choices for sequencing', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='status_delivery',
            field=models.CharField(choices=[('initial', 'not started'), ('in_progress', 'in progress'), ('complete', 'complete'), ('complete_warnings', 'complete with warnings'), ('closed', 'received'), ('failed', 'canceled'), ('canceled', 'canceled confirmed'), ('skipped', 'skipped')], default='initial', help_text='Choices for sequencing', max_length=50),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='status_sequencing',
            field=models.CharField(choices=[('initial', 'not started'), ('in_progress', 'in progress'), ('complete', 'complete'), ('complete_warnings', 'complete with warnings'), ('closed', 'released'), ('failed', 'failed'), ('canceled', 'failured confirmed')], default='initial', help_text='Choices for sequencing', max_length=50),
        ),
    ]
