# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0013_auto_20180621_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcodeset',
            name='set_type',
            field=models.CharField(choices=[('generic', 'generic'), ('10x_genomics', '10x genomics convention')], default='generic', help_text='Type of barcode set.', max_length=100),
        ),
    ]
