# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-31 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcells', '0014_barcodeset_set_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='barcode_mismatches',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of mismatches to allow', null=True),
        ),
    ]
