# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of the barcode adapter set', max_length=100)),
                ('short_name', models.CharField(db_index=True, help_text='Short, unique identifier of barcode adapter set', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeSetEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('sequence', models.CharField(max_length=200)),
                ('barcode_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='flowcells.BarcodeSet')),
            ],
        ),
        migrations.CreateModel(
            name='SequencingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_id', models.CharField(help_text='Vendor ID of the machine', max_length=100)),
                ('label', models.CharField(help_text='Short name of the machine', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description regarding the machine<a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.', null=True)),
                ('machine_model', models.CharField(choices=[('MiSeq', 'MiSeq'), ('MiniSeq', 'MiniSeq'), ('NextSeq500', 'NextSeq 500'), ('HiSeq1000', 'HiSeq 1000'), ('HiSeq1500', 'HiSeq 1500'), ('HiSeq3000', 'HiSeq 3000'), ('HiSeq4000', 'HiSeq 4000'), ('other', 'Other')], help_text='The model of the machine', max_length=100)),
                ('slot_count', models.IntegerField(default=1)),
                ('dual_index_workflow', models.CharField(choices=[('A', 'MiSeq, HiSeq <=2500'), ('B', 'MiniSeq, NextSeq, HiSeq >=3000')], default='A', help_text='Workflow to use for dual indexing', max_length=10)),
            ],
        ),
    ]
