# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequencingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(help_text='Vendor ID of the machine', max_length=100)),
                ('label', models.CharField(help_text='Short name of the machine', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description regarding the machine<a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a> allowed, but no raw HTML. Examples: **bold**, *italic*, indent 4 spaces for a code block.', null=True)),
                ('machine_model', models.CharField(help_text='The model of the machine', max_length=100)),
                ('slot_count', models.IntegerField(default=1)),
                ('dual_index_workflow', models.CharField(choices=[('A', 'MiSeq, HiSeq <=2500'), ('B', 'MiniSeq, NextSeq, HiSeq >=3000')], default='A', help_text='Workflow to use for dual indexing', max_length=10)),
            ],
        ),
    ]
